# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e28321ec15628d884cdc19ebfa5c0409840c7c575f9988ada81b1e09f1a7feadde580444a14a37350687b6102776d0a98057866eedf29fb6133073ab08272fed

test:
  secret_key_base: 66da2c6bc85c122b10a31254ddcc3f5827e6cb6ad7078c92bf028f7261f8431d3523ee8fe6fc1865742ddab7243d3df36b9e9dc6742046d21d7d1a9ffaf3a9b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
